title: Syllabus Showcase
description: 展示一些文件
baseurl: ""
url: "https://fangquinlan.github.io"
theme: minimal
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
collections:
  sylla:
    output: true
    permalink: /courses/:name/

