title: Fang Quinlan's Syllabus Showcase
description: 展示一些syllabus文件。
baseurl: ""
url: "https://fangquinlan.github.io"
theme: jekyll-theme-minimal
markdown: kramdown
collections:
  sylla:
    output: true
    permalink: /courses/:name/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
